#
# Copyright (C) 2023 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# UN1CA debloat list
# - Add entries inside the specific partition containing that file (<PARTITION>_DEBLOAT+="")
# - DO NOT add the partition name at the start of any entry (eg. "/system/dpolicy_system")
# - DO NOT add a slash at the start of any entry (eg. "/dpolicy_system")

# Samsung Defex policy
SYSTEM_DEBLOAT+="
dpolicy_system
"
VENDOR_DEBLOAT+="
etc/dpolicy
"

# Samsung SIM Unlock
SYSTEM_DEBLOAT+="
system/bin/ssud
system/etc/init/ssu_r12sxxx.rc
system/etc/init/ssu.rc
system/etc/permissions/privapp-permissions-com.samsung.ssu.xml
system/etc/sysconfig/samsungsimunlock.xml
system/lib64/android.security.securekeygeneration-ndk.so
system/lib64/vendor.samsung.hardware.security.ssu-V1-ndk.so
system/lib64/libssu_keystore2.so
system/priv-app/SsuService
"

# Recovery restoration script
VENDOR_DEBLOAT+="
recovery-from-boot.p
bin/install-recovery.sh
etc/init/vendor_flash_recovery.rc
"

# Apps debloat
PRODUCT_DEBLOAT+="
app/AssistantShell
app/Chrome64
app/Duo
app/Gmail2
app/Maps
app/YouTube
overlay/GmsConfigOverlaySearchSelector.apk
priv-app/Messages
priv-app/SearchSelector
"

SYSTEM_DEBLOAT+="
system/app/CarrierDefaultApp
system/app/ccinfo
system/app/ChromeCustomizations
system/app/Fast
system/app/FBAppManager_NS
system/app/KidsHome_Installer
system/app/MAPSAgent
system/app/MDMApp
system/app/PlayAutoInstallConfig
system/app/Rampart
system/app/SamsungPassAutofill_v1
system/app/SamsungTTSVoice_ar_AE_m00
system/app/SamsungTTSVoice_de_DE_f00
system/app/SamsungTTSVoice_en_GB_f00
system/app/SamsungTTSVoice_es_ES_f00
system/app/SamsungTTSVoice_es_MX_f00
system/app/SamsungTTSVoice_es_US_f00
system/app/SamsungTTSVoice_fr_FR_f00
system/app/SamsungTTSVoice_hi_IN_f00
system/app/SamsungTTSVoice_id_ID_f00
system/app/SamsungTTSVoice_it_IT_f00
system/app/SamsungTTSVoice_pl_PL_f00
system/app/SamsungTTSVoice_pt_BR_f00
system/app/SamsungTTSVoice_ru_RU_f00
system/app/SamsungTTSVoice_th_TH_f00
system/app/SamsungTTSVoice_vi_VN_f00
system/app/SilentLog
system/app/SimAppDialog
system/app/Traceur
system/app/UniversalMDMClient
system/app/WifiGuider
system/etc/default-permissions/default-permissions-com.sec.spp.push.xml
system/etc/init/digitalkey_init_ble_tss2.rc
system/etc/init/samsung_pass_authenticator_service.rc
system/etc/permissions/authfw.xml
system/etc/permissions/com.samsung.feature.ipsgeofence.xml
system/etc/permissions/com.samsung.feature.samsungpositioning.xml
system/etc/permissions/org.carconnectivity.android.digitalkey.rangingintent.xml
system/etc/permissions/org.carconnectivity.android.digitalkey.secureelement.xml
system/etc/permissions/privapp-permissions-com.microsoft.skydrive.xml
system/etc/permissions/privapp-permissions-com.samsung.android.app.updatecenter.xml
system/etc/permissions/privapp-permissions-com.samsung.android.authfw.xml
system/etc/permissions/privapp-permissions-com.samsung.android.carkey.xml
system/etc/permissions/privapp-permissions-com.samsung.android.dkey.xml
system/etc/permissions/privapp-permissions-com.samsung.android.ipsgeofence.xml
system/etc/permissions/privapp-permissions-com.samsung.android.samsungpass.xml
system/etc/permissions/privapp-permissions-com.samsung.android.samsungpositioning.xml
system/etc/permissions/privapp-permissions-com.samsung.android.spayfw.xml
system/etc/permissions/privapp-permissions-com.samsung.oda.service.xml
system/etc/permissions/privapp-permissions-com.sec.android.diagmonagent.xml
system/etc/permissions/privapp-permissions-com.sec.android.soagent.xml
system/etc/permissions/privapp-permissions-com.sec.bcservice.xml
system/etc/permissions/privapp-permissions-com.sec.imslogger.xml
system/etc/permissions/privapp-permissions-com.sec.spp.push.xml
system/etc/permissions/privapp-permissions-com.skms.android.agent.xml
system/etc/permissions/privapp-permissions-com.wssyncmldm.xml
system/etc/permissions/privapp-permissions-meta.xml
system/etc/PF_TA
system/etc/sysconfig/digitalkey.xml
system/etc/sysconfig/meta-hiddenapi-package-allowlist.xml
system/etc/sysconfig/preinstalled-packages-com.samsung.android.dkey.xml
system/etc/sysconfig/preinstalled-packages-com.samsung.android.spayfw.xml
system/etc/sysconfig/samsungauthframework.xml
system/etc/sysconfig/samsungpassapp.xml
system/etc/sysconfig/samsungpushservice.xml
system/hidden/SmartTutor
system/preload/Facebook_stub_preload
system/priv-app/AppUpdateCenter
system/priv-app/AREmoji
system/priv-app/AREmojiEditor
system/priv-app/AuthFramework
system/priv-app/BCService
system/priv-app/CpAgent
system/priv-app/DiagMonAgent94
system/priv-app/DigitalKey
system/priv-app/EnhancedAttestationAgent
system/priv-app/FBInstaller_NS
system/priv-app/FBServices
system/priv-app/FotaAgent
system/priv-app/ImsLogger
system/priv-app/IpsGeofence
system/priv-app/OdaService
system/priv-app/OMCAgent5
system/priv-app/OneDrive_Samsung_v3
system/priv-app/PaymentFramework
system/priv-app/SamsungCarKeyFw
system/priv-app/SamsungPass
system/priv-app/SamsungPositioning
system/priv-app/SKMSAgent
system/priv-app/SOAgent75
system/priv-app/SPPPushClient
system/priv-app/StickerFaceARAvatar
system/priv-app/YourPhone_P1_5
"

PRISM_DEBLOAT+="
app
etc
HWRDB
preload
priv-app
sipdb
"

OPTICS_DEBLOAT+="
configs
"

#
# Copyright (C) 2023 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Debloat list for the Exynos 9820 platform
# - Add entries inside the specific partition containing that file (<PARTITION>_DEBLOAT+="")
# - DO NOT add the partition name at the start of any entry (eg. "/system/dpolicy_system")
# - DO NOT add a slash at the start of any entry (eg. "/dpolicy_system")

# Camera SDK
SYSTEM_DEBLOAT+="
system/etc/default-permissions/default-permissions-com.samsung.android.globalpostprocmgr.xml
system/etc/default-permissions/default-permissions-com.samsung.petservice.xml
system/etc/default-permissions/default-permissions-com.samsung.videoscan.xml
system/etc/permissions/cameraservice.xml
system/etc/permissions/privapp-permissions-com.samsung.android.globalpostprocmgr.xml
system/etc/permissions/privapp-permissions-com.samsung.petservice.xml
system/etc/permissions/privapp-permissions-com.samsung.videoscan.xml
system/etc/permissions/sec_camerax_impl.xml
system/etc/permissions/sec_camerax_service.xml
system/framework/sec_camerax_impl.jar
system/framework/scamera_sep.jar
system/priv-app/GlobalPostProcMgr
system/priv-app/PetService
system/priv-app/SCameraSDKService
system/priv-app/sec_camerax_service
system/priv-app/VideoScan
"

# Wi-Fi Hotspot Overlays
PRODUCT_DEBLOAT+="
overlay/SoftapOverlay6GHz
overlay/SoftapOverlayDualAp
overlay/SoftapOverlayOWE
product\overlay\AccentColorBlack
product\overlay\AccentColorCinnamon
product\overlay\AccentColorGreen
product\overlay\AccentColorOcean
product\overlay\AccentColorOrchid
product\overlay\AccentColorPurple
product\overlay\AccentColorSpace
product\overlay\DisplayCutoutEmulationCorner
product\overlay\DisplayCutoutEmulationDouble
product\overlay\DisplayCutoutEmulationTall
product\overlay\FontNotoSerifSource
product\overlay\IconPackCircularAndroid
product\overlay\IconPackCircularLauncher
product\overlay\IconPackCircularSettings
product\overlay\IconPackCircularSystemUI
product\overlay\IconPackCircularThemePicker
product\overlay\IconPackFilledAndroid
product\overlay\IconPackFilledLauncher
product\overlay\IconPackFilledSettings
product\overlay\IconPackFilledSystemUI
product\overlay\IconPackFilledThemePicker
product\overlay\IconPackRoundedAndroid
product\overlay\IconPackRoundedLauncher
product\overlay\IconPackRoundedSettings
product\overlay\IconPackRoundedSystemUI
product\overlay\IconShapeRoundedRect
product\overlay\IconShapeSquare
product\overlay\IconShapeSquircle
product\overlay\IconShapeTeardrop
product\overlay\IconShapePebble
product\overlay\IconShapeTaperedRect
product\overlay\IconShapeVessel
"

# StorageShare (kSMBd)
SYSTEM_DEBLOAT+="
system\container
system\containers
system\preloadedsso
system\preloadedkiosk
system\tima_measurement_info
system\tts
system\voicebargeindata
system\hidden
system\heimdallddata
system\recovery-from-boot.p
system\etc\epdg
system\etc\textclassifier
system\etc\theme
system\etc\treble_sepolicy_tests_26.0
system\etc\treble_sepolicy_tests_27.0
system\etc\treble_sepolicy_tests_28.0
system\etc\permissions\knoxsdk_edm.xml
system\etc\permissions\knoxsdk_mdm.xml
system\etc\permissions\privapp-permissions-com.samsung.android.mdx.xml
system\etc\permissions\privapp-permissions-com.sec.android.app.billing.xml
system\etc\permissions\privapp-permissions-com.samsung.android.app.settings.bixby.xml
system\etc\permissions\privapp-permissions-com.samsung.android.bixby.agent.xml
system\etc\permissions\privapp-permissions-com.samsung.android.bixby.service.xml
system\etc\permissions\privapp-permissions-com.samsung.android.bixby.wakeup.xml
system\etc\permissions\privapp-permissions-com.samsung.systemui.bixby2.xml
system\etc\permissions\privapp-permissions-com.samsung.android.bixbyvision.framework.xml
system\etc\permissions\privapp-permissions-com.samsung.android.visionarapps_v1.xml
system\etc\permissions\privapp-permissions-com.samsung.android.visionintelligence_v3.xml
system\etc\permissions\privapp-permissions-com.samsung.android.keyguardmgsupdator.xml
system\etc\permissions\privapp-permissions-com.samsung.android.mateagent.xml
system\etc\permissions\privapp-permissions-com.samsung.android.game.gamehome.xml
system\etc\permissions\privapp-permissions-com.samsung.android.game.gamehome.xml
system\etc\permissions\privapp-permissions-com.samsung.android.game.gos.xml
system\etc\permissions\privapp-permissions-facebook.xml
system\etc\permissions\privapp-permissions-com.sec.spp.push.xml
system\etc\permissions\privapp-permissions-de.axelspringer.yana.zeropage.xml
system\etc\sysconfig\facebook-hiddenapi-package-whitelist.xml
system\etc\sysconfig\google_duo.xml
system\etc\sysconfig\google_turbo.xml
system\lib\libknoxdrawglfunction.so
system\lib\libknox_encryption.so
system\lib\libskmipc.a
system\app\ARZone
system\app\AutoBackup_release
system\app\AASAservice
system\app\AllShareCastPlayer
system\app\AllShareAware
system\app\AllshareFileShareClient
system\app\AllshareFileShareServer
system\app\AllshareFileShare
system\app\AllshareMediaShare
system\app\AntHalService
system\app\ANTPlusPlugins
system\app\ANTPlusTest
system\app\AssistantMenu_M
system\app\ARCore
system\app\ARDrawing
system\app\AutomationTest_FB
system\app\BeamService
system\app\Blurb
system\app\Books
system\app\Bridge
system\app\ChatON_MARKET
system\app\BasicDreams
system\app\BBCAgent
system\app\BCService
system\app\Bridge
system\app\BixbyWakeup
system\app\BluetoothMidiService
system\app\BluetoothTest
system\app\bootagent
system\app\ColorBlind
system\app\de.pizza.lib
system\app\DigitalClock21
system\app\DioDict3Service
system\app\Drive
system\app\Dropbox
system\app\DropboxOOBE
system\app\OperaMax
system\app\DualClockDigital
system\app\EasyFavoritesContactsWidget
system\app\EasySettings
system\app\ELMAgent
system\app\ChocoEUKor
system\app\CoolEUKor
system\app\CarmodeStub
system\app\ContainerAgent
system\app\ContainerEventsRelayManager
system\app\BuiltInPrintService
system\app\DictDiotekForSec
system\app\DictDiotek
system\app\DictDiotek_update
system\app\DRParser
system\app\DuoStub
system\app\EasymodeContactsWidget81
system\app\EasymodeContactsWidget
system\app\EdmSimPinService
system\app\EmergencyLauncher
system\app\EmergencyModeService
system\app\EmergencyProvider
system\app\Facebook_stub
system\app\FBInstagram_stub
system\app\FactoryAirCommandManager
system\app\FactoryCameraFB
system\app\FBAppManager
system\app\FBAppManager_NS
system\app\FlipboardBriefing
system\app\FlipboardBriefingPanel
system\app\Foundation
system\app\GearManagerStub
system\app\Gmail2
system\app\GoogleEarth
system\app\GoogleSearchWidget
system\app\GameOptimizer
system\app\Hangouts
system\app\GooglePrintRecommendationService
system\app\GoogleTTS
system\app\Internet
system\app\Kies
system\app\KidsHome_Installer
system\app\KLMSAgent
system\app\KNOXAgent
system\app\KnoxAttestationAgent
system\app\KnoxSetupWizardClient
system\app\KnoxSetupWizardStub
system\app\KNOXStore
system\app\KNOXStub
system\app\KnoxVpnServices
system\app\RCPComponents
system\app\KnoxAppsUpdateAgent
system\app\KnoxFolderContainer
system\app\KnoxSwitcher
system\app\MyKNOXSetupWizard
system\app\MyKNOXManager
system\app\LinkSharing_v10
system\app\LinkSharing_v11
system\app\LinkSharing_v34
system\app\LinkSharing_v40
system\app\Maps
system\app\MapsGo
system\app\MDMApp
system\app\Netflix_activationCommon
system\app\Netflix_stub
system\app\PartnerBookmarksProvider
system\app\PlayAutoInstallConfig
system\app\Personalization
system\app\PrintSpooler
system\app\SafetyInformation
system\app\SPDClient
system\app\SecurityLogAgent
system\app\RoseEUKor
system\app\SwitchKnoxI
system\app\SwitchKnoxII
system\app\SamsungDaily
system\app\SamsungOne
system\app\SamsungPassAutofill_v1
system\app\SamsungTTS
system\app\SBrowserEdge
system\app\SBrowser_7.2
system\app\SBrowser_9.0_Removable
system\app\SBrowser_11.0_Removable
system\app\SCPMClient_N
system\app\SecHTMLViewer
system\app\SmartReminder
system\app\STalkback
system\app\VisionARApps1.1
system\app\TEEgrisTuiService
system\app\talkback
system\app\UniversalMDMClient
system\app\VoiceNote_5.0
system\app\WallpaperBackup
system\app\WifiGuider
system\app\VisionARApps_stub
system\app\WebManual
system\app\Weather_SEP9.1
system\app\Weather_SEP10.1
system\app\Weather_SEP11.0
system\app\Weather_SEP12.0
system\app\Weather_SEP12.1
system\app\Weather2017
system\app\WeatherWidget2017
system\app\Weather_Stub
system\app\YouTube
system\priv-app\AndroidAutoStub
system\priv-app\ANTRadioService
system\priv-app\AREmoji
system\priv-app\AREmojiEditor
system\priv-app\AuthFramework
system\priv-app\AutoDoodle_Q
system\priv-app\AvatarEmojiSticker_Q
system\priv-app\AvatarEmojiSticker_Canvas
system\priv-app\Bridge
system\priv-app\Bixby
system\priv-app\BixbyHome
system\priv-app\BixbyAgentDummy
system\priv-app\BixbyGlobalAction
system\priv-app\BixbyPLMSync
system\priv-app\BixbyVoiceInput
system\priv-app\BixbyAgentStub
system\priv-app\BixbyService
system\priv-app\BixbyVisionFramework3
system\priv-app\BixbyVisionFramework3.5
system\priv-app\CIDManager
system\priv-app\ContainerAgent
system\priv-app\ContainerEventsRelayManager
system\priv-app\CtsShimPrivPrebuilt
system\priv-app\DevicePersonalizationServices
system\priv-app\DeviceQualityAgent
system\priv-app\DiagMonAgent
system\priv-app\DigitalWellbeing
system\priv-app\Excel_SamsungStub
system\priv-app\Word_SamsungStub
system\priv-app\LinkedIn_SamsungStub
system\priv-app\EpdgService
system\priv-app\EasySetup
system\priv-app\Excel_SamsungStub
system\priv-app\EmergencyInfo
system\priv-app\EmojiUpdater
system\priv-app\FBInstaller_NS
system\priv-app\FBInstaller
system\priv-app\FBServices
system\priv-app\FotaAgent
system\priv-app\Fast
system\priv-app\Fmm
system\priv-app\FusedLocation
system\priv-app\RubinVersion25
system\priv-app\RubinVersion26
system\priv-app\GalaxyAppsWidget_Phone_Dream
system\priv-app\GalaxyAppsWidget_Phone_Hero
system\priv-app\GameHome
system\priv-app\GameOptimizingService
system\priv-app\GameTools_Dream
system\priv-app\GoogleFeedback
system\priv-app\GooglePartnerSetup
system\priv-app\ManagedProvisioning
system\priv-app\MultipleWallpaperResourceA10
system\priv-app\MultipleWallpaperResourceA20
system\priv-app\MultipleWallpaperResourceA30
system\priv-app\MultipleWallpaperResourceA30s
system\priv-app\MultipleWallpaperResourceA40
system\priv-app\MultipleWallpaperResourceA50s
system\priv-app\MultipleWallpaperResourceA50
system\priv-app\MultipleWallpaperResourceA60
system\priv-app\MultipleWallpaperResourceA70Q
system\priv-app\MultipleWallpaperResourceM20
system\priv-app\MultipleWallpaperResourceM30
system\priv-app\MultipleWallpaperResource1S10
system\priv-app\MultipleWallpaperResource1S10Full
system\priv-app\MultipleWallpaperResource2S10
system\priv-app\MultipleWallpaperResourceS10+5G
system\priv-app\MyGalaxy
system\priv-app\HealthService
system\priv-app\SHealth5
system\priv-app\SHealth6PAR
system\priv-app\SHealthStub
system\priv-app\HybridRadio
system\priv-app\LinkToWindowsService
system\priv-app\LiveStickers
system\priv-app\IpsGeofence
system\priv-app\MateAgent
system\priv-app\OmaCP
system\priv-app\OMCAgent5
system\priv-app\OneDrive_Samsung_v3
system\priv-app\OneDrive_Samsung_v3_Removable
system\priv-app\PaymentFramework
system\priv-app\PreloadInstaller
system\priv-app\PowerPlanning
system\priv-app\PowerPoint_SamsungStub
system\priv-app\ringtoneBR
system\priv-app\Routines
system\priv-app\StorageManager
system\priv-app\SamsungConnect
system\priv-app\SamsungConnect_Stub
system\priv-app\SamsungMax
system\priv-app\SamsungMembers
system\priv-app\SamsungMembersStub
system\priv-app\SamsungBilling
system\priv-app\SamsungMultiConnectivity
system\priv-app\SamsungPass
system\priv-app\SamsungPass_1.1
system\priv-app\SamsungPass_1.2
system\priv-app\SamsungPayStub
system\priv-app\SamsungPayStubMini
system\priv-app\SamsungPositioning
system\priv-app\SamsungLink20
system\priv-app\SamsungLinkPlatform
system\priv-app\SamsungMusic_20
system\priv-app\SamsungWallet_Stub
system\priv-app\Samsungservice2_xxhdpi
system\priv-app\SamsungVideo
system\priv-app\SecVideo
system\priv-app\SecVideoPlayer
system\priv-app\SecLiveWallpapersPicker
system\priv-app\ShareVideo
system\priv-app\SNoteProvider
system\priv-app\SetupIndiaServicesTnC
system\priv-app\S Secure
system\priv-app\SSecure
system\priv-app\S_Secure
system\priv-app\Sprotect
system\priv-app\sCloudBackupApp
system\priv-app\sCloudDataRelay
system\priv-app\sCloudDataSync
system\priv-app\sCloudQuotaApp
system\priv-app\sCloudSyncCalendar
system\priv-app\sCloudSyncContacts
system\priv-app\sCloudSyncSBrowser
system\priv-app\sCloudSyncSNote
system\priv-app\sCloudSyncSNote3
system\priv-app\SFinder
system\priv-app\SHealth3_5
system\priv-app\SMemo2
system\priv-app\SNS
system\priv-app\SNoteProvider
system\priv-app\SPDClient
system\priv-app\SPPPushClient_Prod
system\priv-app\StoryAlbum2013_L
system\priv-app\StoryAlbumWidget
system\priv-app\SecureFolder
system\priv-app\SecureFolder_Alive
system\priv-app\SendHelpMessage
system\priv-app\serviceModeApp_FB
system\priv-app\SettingsBixby
system\priv-app\SKMSAgent
system\priv-app\SmartEpdgTestApp
system\priv-app\SmartManager_v3
system\priv-app\SmartManager_v3_DeviceSecurity
system\priv-app\SmartManager_v6_DeviceSecurity
system\priv-app\SPPPushClient
system\priv-app\StickerCenter
system\priv-app\StickerFaceAR3
system\priv-app\StickerFaceARExp
system\priv-app\StickerFaceARFrame
system\priv-app\StickerStamp
system\priv-app\StickerFaceARAvatar
system\priv-app\SystemUIBixby2
system\priv-app\SVoice
system\priv-app\SVoice_1.0
system\priv-app\SVoiceLang_EnglishPack_GB_1.0
system\priv-app\SVoiceLang_EnglishPack_US_1.0
system\priv-app\SVoiceLang_FrenchPack_1.0
system\priv-app\SVoiceLang_GermanPack_DE_1.0
system\priv-app\SVoiceLang_ItalianPack_IT_1.0
system\priv-app\SVoiceLang_RussianPack_RU_1.0
system\priv-app\SVoiceLang_SpanishPack_ES_1.0
system\priv-app\SVoicePLM
system\priv-app\SVoicePLM_1.0
system\priv-app\LogWriter
system\priv-app\TADownloader
system\priv-app\Tag
system\priv-app\TaPackAuthFw
system\priv-app\Turbo
system\priv-app\UltraDataSaving_O
system\priv-app\UltraDataSaving_P
system\priv-app\UIBCVirtualSoftkey
system\priv-app\Upday
system\priv-app\Velvet
system\priv-app\YourPhone_P1_5
system\priv-app\YourPhone_Stub
system\priv-app\KeyguardWallpaperUpdator
system\priv-app\KeyguardMGSUpdator
system\priv-app\KnoxCore
system\priv-app\KnoxGuard
system\priv-app\KnoxKeyChain
system\priv-app\SOAgent
system\priv-app\knoxanalyticsagent
system\priv-app\knoxvpnproxyhandler
system\priv-app\KLMSAgent
system\priv-app\KNOXAgent
system\priv-app\KnoxAttestationAgent
system\priv-app\KnoxSetupWizardClient
system\priv-app\KnoxSetupWizardStub
system\priv-app\KNOXStore
system\priv-app\KNOXStub
system\priv-app\KnoxVpnServices
system\priv-app\RCPComponents
system\priv-app\KnoxAppsUpdateAgent
system\priv-app\KnoxFolderContainer
system\priv-app\KnoxSwitcher
system\priv-app\MyKNOXSetupWizard
system\priv-app\MyKNOXManager
system\priv-app\NSFusedLocation_v5.0_UPG
system\priv-app\SPDClient
system\priv-app\SwitchKnoxI
system\priv-app\SwitchKnoxII
system/bin/ksmbd.addshare
system/bin/ksmbd.adduser
system/bin/ksmbd.control
system/bin/ksmbd.mountd
system/bin/ksmbd.tools
system/etc/default-permissions/default-permissions-com.samsung.android.hwresourceshare.storage.xml
system/etc/init/ksmbd.rc
system/etc/permissions/privapp-permissions-com.samsung.android.hwresourceshare.storage.xml
system/etc/sysconfig/preinstalled-packages-com.samsung.android.hwresourceshare.storage.xml
system/etc/ksmbd.conf
system/priv-app/StorageShare
"
# eSIM
if $SOURCE_IS_ESIM_SUPPORTED; then
    if ! $TARGET_IS_ESIM_SUPPORTED; then
        SYSTEM_DEBLOAT+="
        system/etc/permissions/privapp-permissions-com.samsung.android.app.esimkeystring.xml
        system/etc/permissions/privapp-permissions-com.samsung.euicc.mep.xml
        system/etc/sysconfig/preinstalled-packages-com.samsung.android.app.esimkeystring.xml
        system/etc/sysconfig/preinstalled-packages-com.samsung.euicc.xml
        system/priv-app/EsimKeyString
        system/priv-app/EsimClient
        system/priv-app/EuiccService
        "
    fi
fi
